version:  '3.9'

services:
  postgres:
    image: postgres:15
    container_name: db_tramite
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network   


volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge